title: Lecture notes for IMPRS for Quantum Dynamics and Control 2024
author: Attila Cangi 
copyright: '2024'
logo: 'Logo_small.png'

# Short description about the book
description: >-
  Introduction to Machine Learning in Physics.

# Information about where the book exists on the web
#  url                       : https://github.com/acangi/lecture_notes_imprs_qdc_2024  # Online location of your book
#  path_to_book              : mini_book  # Optional path to your book, relative to the repository root
#  branch                    : master  # Which branch of the repository should be used when creating links (optional)

# Notebook interface
#launch_buttons:
#  colab_url: "https://colab.research.google.com/github/acangi/lecture_notes_imprs_qdc_2024/mini_book/docs"

# Jupyter notebook settings
execute:
  execute_notebooks           : false

# TOC settings
number_toc_chapters           : false

# Interact link settings
notebook_interface            : "notebook"

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# Sphinx settings
sphinx:
  config:
    html_theme_options:
      extra_footer: 'Lecture notes for IMPRS for Quantum Dynamics and Control 2024'
#      repository_url: https://github.com/acangi/lecture_notes_imprs_qdc_2024 
#      nb_repository_url: https://github.com/acangi/lecture_notes_imprs_qdc_2024/main/mini_book
#      launch_buttons:
#        notebook_interface: classic
#        colab_url: https://colab.research.google.com